import express from "express";
import { createNote } from "../controllers/note.controller.js";
import { getNotes } from "../controllers/note.controller.js";
import { getNoteById } from "../controllers/note.controller.js";
import { updateNotes } from "../controllers/note.controller.js";
import { deleteNotes } from "../controllers/note.controller.js";
import { addComment, deleteComment, addReply } from "../controllers/note.controller.js";
const router = express.Router();
router.post("/create", createNote);
router.get("/get", getNotes);
router.get("/:id", getNoteById);
router.put("/update/:id", updateNotes);
router.delete("/delete/:id", deleteNotes);
router.post("/:id/comments", addComment);
router.post("/:id/comments/:commentId/replies", addReply);
router.delete("/:id/comments/:commentId", deleteComment);
export default router;